### ISSUE TITLE
Alternative Provider/Source

### ISSUE THREAD

**Issue by kraddock** [Sat178/UrlTok2#3]
Hey! Love the new app! I have a suggestion - until TikMate could download real HD again (after TikTok changed/removed the endpoint to the file), could you add an alternative provider - https://www.tikwm.com/ - it has a workaround to download HD/original files (best quality). Thanks!

**Comment by Sat178** [comment]
Great suggestion, thanks.

I will make an option to change provider in the config in the next update!
